/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
* other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
* EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
* SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
* SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
* this software. By using this software, you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2019 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

extern st_ble_gatts_db_cfg_t g_gatt_db_table;

typedef enum
{
    BLE_INVALID_ATTR_HDL = 0x0000,
    BLE_GAPS_DECL_HDL = 0x0001,
    BLE_GAPS_DEV_NAME_DECL_HDL = 0x0002,
    BLE_GAPS_DEV_NAME_VAL_HDL = 0x0003,
    BLE_GAPS_APPEARANCE_DECL_HDL = 0x0004,
    BLE_GAPS_APPEARANCE_VAL_HDL = 0x0005,
    BLE_GAPS_PER_PREF_CONN_PARAM_DECL_HDL = 0x0006,
    BLE_GAPS_PER_PREF_CONN_PARAM_VAL_HDL = 0x0007,
    BLE_GAPS_CENT_ADDR_RSLV_DECL_HDL = 0x0008,
    BLE_GAPS_CENT_ADDR_RSLV_VAL_HDL = 0x0009,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_DECL_HDL = 0x000A,
    BLE_GAPS_RSLV_PRIV_ADDR_ONLY_VAL_HDL = 0x000B,
    BLE_GATS_DECL_HDL = 0x000C,
    BLE_GATS_SERV_CHGED_DECL_HDL = 0x000D,
    BLE_GATS_SERV_CHGED_VAL_HDL = 0x000E,
    BLE_GATS_SERV_CHGED_CLI_CNFG_DESC_HDL = 0x000F,
    BLE_THPSS_DECL_HDL = 0x0010,
    BLE_THPSS_TEMPERATURE_DECL_HDL = 0x0011,
    BLE_THPSS_TEMPERATURE_VAL_HDL = 0x0012,
    BLE_THPSS_TEMPERATURE_CLI_CNFG_DESC_HDL = 0x0013,
    BLE_THPSS_HUMIDITY_DECL_HDL = 0x0014,
    BLE_THPSS_HUMIDITY_VAL_HDL = 0x0015,
    BLE_THPSS_HUMIDITY_CLI_CNFG_DESC_HDL = 0x0016,
    BLE_THPSS_PRESSURE_DECL_HDL = 0x0017,
    BLE_THPSS_PRESSURE_VAL_HDL = 0x0018,
    BLE_THPSS_PRESSURE_CLI_CNFG_DESC_HDL = 0x0019,
    BLE_RELAY_SERVICES_DECL_HDL = 0x001A,
    BLE_RELAY_SERVICES_DIGITAL_1_DECL_HDL = 0x001B,
    BLE_RELAY_SERVICES_DIGITAL_1_VAL_HDL = 0x001C,
    BLE_RELAY_SERVICES_DIGITAL_1_CLI_CNFG_DESC_HDL = 0x001D,
} e_ble_attr_hdl_t;

#define BLE_GAPS_DEV_NAME_LEN (128)
#define BLE_GAPS_APPEARANCE_LEN (2)
#define BLE_GAPS_PER_PREF_CONN_PARAM_LEN (8)
#define BLE_GAPS_CENT_ADDR_RSLV_LEN (1)
#define BLE_GAPS_RSLV_PRIV_ADDR_ONLY_LEN (1)
#define BLE_GATS_SERV_CHGED_LEN (4)
#define BLE_GATS_SERV_CHGED_CLI_CNFG_LEN (2)
#define BLE_THPSS_TEMPERATURE_LEN (2)
#define BLE_THPSS_TEMPERATURE_CLI_CNFG_LEN (2)
#define BLE_THPSS_HUMIDITY_LEN (2)
#define BLE_THPSS_HUMIDITY_CLI_CNFG_LEN (2)
#define BLE_THPSS_PRESSURE_LEN (4)
#define BLE_THPSS_PRESSURE_CLI_CNFG_LEN (2)
#define BLE_RELAY_SERVICES_DIGITAL_1_LEN (2)
#define BLE_RELAY_SERVICES_DIGITAL_1_CLI_CNFG_LEN (2)

#endif /* GATT_DB_H */